spring:
  application:
    name: SpringBootGrpc2
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/vanilladb?useSSL=false&verifyServerCertificate=false
    username: root
    password: 123

#security:
#    user:
#      password: password
#    oauth2:
#      resource:
#        filter-order: 3



server:
  port: 8453
  ssl:
    key-store: classpath:localhost.jks
    key-store-password: binara
    key-alias: localhost
    key-password: binara
    key-store-provider: SUN
    key-store-type: JKS


grpc:
  server:
    port: 9095
    security:
      enabled: true
      certificate-chain-path: /home/binara/Documents/Other_Projects/Vindana_Viztaa_Enterprise/Sample_Codes/SpringBootGrpc2/src/main/resources/localhost-cert.crt
      certificate-path: /home/binara/Documents/Other_Projects/Vindana_Viztaa_Enterprise/Sample_Codes/SpringBootGrpc2/src/main/resources/localhost-primarykey.key
#      jwks_uri: /home/binara/Documents/Other_Projects/Vindana_Viztaa_Enterprise/Sample_Codes/SpringBootGrpc2/src/main/resources/localhost-publicKey-JWK.json
#      certificate-path: localhost.p12
#  client:
#    ssl-server:
#      host:
#        - 127.0.0.1
#      port:
#        - 9095
#  authentication:
#    providers:
#    - id: oauth2
#      # The value below should be unique
#      issuer: https://localhost:8453/oauth/token
#      jwks_uri: /home/binara/Documents/Other_Projects/Vindana_Viztaa_Enterprise/Sample_Codes/SpringBootGrpc2/src/main/resources/localhost-publicKey-JWK.json
#    rules:
#    - selector: "*"
#      requirements:
#        - provider_id: oauth2


#security:
#  oauth2:
#    resource:
#      jwt:
#        # Tells the JWT framework to fetch the public key from the authorization server during startup
#        # Note: The authorization server needs to be running...
#        key-uri: /home/binara/Documents/Other_Projects/Vindana_Viztaa_Enterprise/Sample_Codes/SpringBootGrpc2/src/main/resources/localhost-publicKey-JWK.json
#      jwk:
#        key-set-uri: /home/binara/Documents/Other_Projects/Vindana_Viztaa_Enterprise/Sample_Codes/SpringBootGrpc2/src/main/resources/localhost-publicKey-JWK.json


#db:
#  driver: com.mysql.jdbc.Driver
#  url: jdbc:mysql://localhost:3306/vanilladb?useSSL=false&verifyServerCertificate=false
#  username: root
#  password: 123

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: create
#  datasource:
#    url: jdbc:mysql://localhost:3306/vanilladb?useSSL=false&verifyServerCertificate=false
#    username: root
#    password: 123





#hibernate:
#  dialect: org.hibernate.dialect.MySQL5Dialect
#  hbm2ddl:
#    auto: create
#  ejb:
#    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#  show_sql: false
#  format_sql: true